server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
    path: /error/**
    whitelabel:
      enabled: true
spring:
  main:
     allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
       ddl-auto: create
    properties:
      hibernate:
       format_sql: true
  datasource:
     #      driver-class-name: oracle.jdbc.OracleDriver
     #      url: jdbc:oracle:thin:@localhost:1521:xe
     #      username: isaacweb
     #      password: 1234
     hikari:
       connection-timeout: 60000
       maximum-pool-size: 50
       minimum-idle: 20
       idle-timeout: 10000
       data-source-properties:
         cachePrepStmts: true
         prepStmtCacheSize: 250
         prepStmtCacheSqlLimit: 2048
         useServerPrepStmts: true
     driver-class-name: org.h2.Driver
     url: jdbc:h2:~/active;AUTO_SERVER=TRUE
     username: active
     password: 1234
  thymeleaf:
     cache: false
     check-template-location: true
     encoding: UTF-8
     servlet:
       content-type: text/html
     prefix: classpath:/templates/
     suffix: .html
